### ISSUE TITLE
TSHÀNG-SÌ-KÌ

### ISSUE THREAD

**Issue by DonAnthonyLee** [learn-teochew/tc-bibles#1]
Uá ŭ-ôiⁿ lân-sî ŭ tŏ lo̍k-jîp TSHÀNG-SÌ-KÌ, chiăm-sî soiⁿ pau thâu 50 hio̍h. Nín tī-nâng ŭ siŏⁿ àiⁿ tsò-che̍k-ē lâi --kâi, hó tùi tŏiⁿ 51 hio̍h mue̍h-khí, mài tăi-ke-nâng khang-khuè sio-têng-thăⁿ.

**Comment by kbseah** [comment]
tsōi-sià! uá nā-sĩ lo̍k-jip Tshàng-Sì-kì tsiũ tshông tõin-51 hio̍h kai-sí.
